// GENERATED by tooling/generate-mobile-chat-agents.mjs in the Ghostex main repo; do not
// edit by hand. Source: SESSION_CHAT_SUPPORTED_AGENTS in packages/shared/session-chat.ts.
// Regenerate with `bun run generate:mobile-chat-agents` there.

export const SESSION_CHAT_SUPPORTED_AGENT_IDS: readonly string[] = ["antigravity","antigravity-cli","agy","claude","openclaude","codex","cursor","grok","grok-build","hermes","hermes-agent","pi","omp","zcode"];
