// The Web preview loads `http://127.0.0.1:<forwarded port>` in a WebView, and
// an Android WebView obeys the app's network security policy. Android's default
// for targetSdk >= 28 is "no cleartext at all", which would fail the preview
// with a blank page, so the app ships a network security config that permits
// cleartext for the loopback host names only. Nothing else in the shipped app is
// allowed to fall back to http: no `usesCleartextTraffic="true"`, no base
// config change, and no other domain in the allowance. Debug builds get a
// second, debug-only copy of the resource that also permits cleartext to the
// Metro dev server — see DEBUG_NETWORK_SECURITY_CONFIG below.
//
// The same plugin also declares the http scheme in <queries>, because
// "Open in browser" hands `http://127.0.0.1:…` to another app on the phone and
// Android 11+ package visibility hides browsers that only match http otherwise.
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

const RESOURCE_NAME = 'network_security_config';

const LOOPBACK_DOMAIN_CONFIG = `    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>`;

const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withLoopbackCleartext.js. Cleartext is permitted for the
  phone's own loopback only, which is where Ghostex's SSH port forwards listen;
  every other destination keeps Android's secure default.
-->
<network-security-config>
${LOOPBACK_DOMAIN_CONFIG}
</network-security-config>
`;

// Setting android:networkSecurityConfig makes Android ignore
// android:usesCleartextTraffic, including the "true" that the debug manifest
// sets so Metro can be reached over http on a LAN address or 10.0.2.4. A debug
// variant therefore needs its own config, and the only difference is the
// base-config that puts that permission back — the loopback allowance is the
// same, and release keeps the loopback-only config above untouched.
const DEBUG_NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Generated by plugins/withLoopbackCleartext.js for debug builds only. Debug
  builds talk to the Metro dev server over http on whatever address the machine
  running it has, so cleartext is permitted everywhere here. The release config
  (app/src/main/res/xml) still allows it for loopback alone.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
${LOOPBACK_DOMAIN_CONFIG}
</network-security-config>
`;

function withNetworkSecurityConfigResource(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const write = (variant, contents) => {
        const xmlDir = path.join(cfg.modRequest.platformProjectRoot, `app/src/${variant}/res/xml`);
        fs.mkdirSync(xmlDir, { recursive: true });
        fs.writeFileSync(path.join(xmlDir, `${RESOURCE_NAME}.xml`), contents);
      };
      write('main', NETWORK_SECURITY_CONFIG);
      write('debug', DEBUG_NETWORK_SECURITY_CONFIG);
      return cfg;
    },
  ]);
}

function withNetworkSecurityConfigManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    application.$['android:networkSecurityConfig'] = `@xml/${RESOURCE_NAME}`;

    const manifest = cfg.modResults.manifest;
    manifest.queries = manifest.queries ?? [];
    if (manifest.queries.length === 0) manifest.queries.push({});
    const queries = manifest.queries[0];
    queries.intent = queries.intent ?? [];
    const declaresHttp = queries.intent.some((intent) =>
      (intent.data ?? []).some((data) => data.$?.['android:scheme'] === 'http')
    );
    if (!declaresHttp) {
      queries.intent.push({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
        category: [{ $: { 'android:name': 'android.intent.category.BROWSABLE' } }],
        data: [{ $: { 'android:scheme': 'http' } }],
      });
    }
    return cfg;
  });
}

module.exports = function withLoopbackCleartext(config) {
  return withNetworkSecurityConfigManifest(withNetworkSecurityConfigResource(config));
};
