#!/usr/bin/env python3
"""Convert the Android fork's ic_ghostex_agent_*.xml vector drawables into a
generated react-native-svg component map (src/assets/agentIcons.generated.tsx).

Icons are tinted uniformly at runtime (matching the Android app's colorFilter
tinting), so every fill/stroke is replaced with the `color` prop.

Usage: python3 scripts/convert-agent-icons.py
"""
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ANDROID_NS = "{http://schemas.android.com/apk/res/android}"
SRC = Path(__file__).resolve().parents[2] / "android/app/src/main/res/drawable"
OUT = Path(__file__).resolve().parents[1] / "src/assets/agentIcons.generated.tsx"


def a(el, name, default=None):
    return el.get(ANDROID_NS + name, default)


def icon_id(fname: str) -> str:
    return fname.replace("ic_ghostex_agent_", "").replace(".xml", "").replace("_", "-")


def component_name(iid: str) -> str:
    return "Icon" + "".join(p.capitalize() for p in iid.split("-"))


def emit_paths(el, out, warnings, depth=0):
    for child in el:
        tag = child.tag.split("}")[-1]
        if tag == "path":
            d = a(child, "pathData")
            if not d:
                continue
            attrs = [f'd="{d}"']
            fill_type = a(child, "fillType")
            if fill_type and fill_type.lower() == "evenodd":
                attrs.append('fillRule="evenodd"')
            stroke_w = a(child, "strokeWidth")
            fill_c = a(child, "fillColor")
            stroke_c = a(child, "strokeColor")
            has_fill = fill_c is not None and fill_c != "#00000000"
            if stroke_c and stroke_w:
                attrs.append(f'stroke={{color}} strokeWidth={{{stroke_w}}}')
                cap = a(child, "strokeLineCap")
                join = a(child, "strokeLineJoin")
                if cap:
                    attrs.append(f'strokeLinecap="{cap}"')
                if join:
                    attrs.append(f'strokeLinejoin="{join}"')
                if not has_fill:
                    attrs.append('fill="none"')
            if has_fill or (not stroke_c):
                attrs.append("fill={color}")
            out.append("      <Path " + " ".join(attrs) + " />")
        elif tag == "group":
            tx = float(a(child, "translateX", 0) or 0)
            ty = float(a(child, "translateY", 0) or 0)
            sx = float(a(child, "scaleX", 1) or 1)
            sy = float(a(child, "scaleY", 1) or 1)
            rot = float(a(child, "rotation", 0) or 0)
            parts = []
            if tx or ty:
                parts.append(f"translate({tx}, {ty})")
            if rot:
                parts.append(f"rotate({rot})")
            if sx != 1 or sy != 1:
                parts.append(f"scale({sx}, {sy})")
            if parts:
                out.append(f'      <G transform="{" ".join(parts)}">')
                emit_paths(child, out, warnings, depth + 1)
                out.append("      </G>")
            else:
                emit_paths(child, out, warnings, depth + 1)
        else:
            warnings.append(f"unhandled element <{tag}>")


def main():
    files = sorted(SRC.glob("ic_ghostex_agent_*.xml"))
    if not files:
        print(f"no drawables found in {SRC}", file=sys.stderr)
        sys.exit(1)
    components = []
    entries = []
    for f in files:
        root = ET.parse(f).getroot()
        vw = a(root, "viewportWidth", "24")
        vh = a(root, "viewportHeight", "24")
        iid = icon_id(f.name)
        cname = component_name(iid)
        body = []
        warnings = []
        emit_paths(root, body, warnings)
        for w in warnings:
            print(f"warning: {f.name}: {w}", file=sys.stderr)
        components.append(
            f"function {cname}({{ size, color }}: AgentIconProps) {{\n"
            f"  return (\n"
            f'    <Svg width={{size}} height={{size}} viewBox="0 0 {vw} {vh}">\n'
            + "\n".join(body)
            + f"\n    </Svg>\n  );\n}}"
        )
        entries.append(f"  '{iid}': {cname},")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// GENERATED by scripts/convert-agent-icons.py from the Android fork's\n"
        "// ic_ghostex_agent_*.xml vector drawables. Do not edit by hand.\n"
        "import * as React from 'react';\n"
        "import Svg, { G, Path } from 'react-native-svg';\n\n"
        "export type AgentIconProps = { size: number; color: string };\n\n"
        + "\n\n".join(components)
        + "\n\nexport const AGENT_ICONS: Record<string, (props: AgentIconProps) => React.JSX.Element> = {\n"
        + "\n".join(entries)
        + "\n};\n"
    )
    print(f"wrote {OUT} ({len(files)} icons)")


if __name__ == "__main__":
    main()
