// GENERATED by tooling/generate-mobile-tabler-icons.mjs in the Ghostex main
// repo from @tabler/icons SVG sources — do not edit by hand. These mirror the
// glyphs packages/core-ui/session-tag-ui.tsx and packages/core-ui/sidebar-command-icon.tsx draw
// in the gpui sidebar. Regenerate with `bun run generate:mobile-tabler-icons`.
import * as React from 'react';
import Svg, { Path } from 'react-native-svg';

export type TablerIconProps = { size: number; color: string; strokeWidth?: number };
export type TablerIconComponent = (props: TablerIconProps) => React.JSX.Element;

function TagBlocked({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 8a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v7a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1l0 -7" stroke={color} />
      <Path d="M7 16v4" stroke={color} />
      <Path d="M7.5 16l9 -9" stroke={color} />
      <Path d="M13.5 16l6.5 -6.5" stroke={color} />
      <Path d="M4 13.5l6.5 -6.5" stroke={color} />
      <Path d="M17 16v4" stroke={color} />
      <Path d="M5 20h4" stroke={color} />
      <Path d="M15 20h4" stroke={color} />
      <Path d="M17 7v-2" stroke={color} />
      <Path d="M7 7v-2" stroke={color} />
    </Svg>
  );
}

function TagBug({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M9 9v-1a3 3 0 0 1 6 0v1" stroke={color} />
      <Path d="M8 9h8a6 6 0 0 1 1 3v3a5 5 0 0 1 -10 0v-3a6 6 0 0 1 1 -3" stroke={color} />
      <Path d="M3 13l4 0" stroke={color} />
      <Path d="M17 13l4 0" stroke={color} />
      <Path d="M12 20l0 -6" stroke={color} />
      <Path d="M4 19l3.35 -2" stroke={color} />
      <Path d="M20 19l-3.35 -2" stroke={color} />
      <Path d="M4 7l3.75 2.4" stroke={color} />
      <Path d="M20 7l-3.75 2.4" stroke={color} />
    </Svg>
  );
}

function TagDesign({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 21a9 9 0 0 1 0 -18c4.97 0 9 3.582 9 8c0 1.06 -.474 2.078 -1.318 2.828c-.844 .75 -1.989 1.172 -3.182 1.172h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25" stroke={color} />
      <Path d="M7.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" stroke={color} />
      <Path d="M11.5 7.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" stroke={color} />
      <Path d="M15.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" stroke={color} />
    </Svg>
  );
}

function TagDone({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" stroke={color} />
      <Path d="M9 12l2 2l4 -4" stroke={color} />
    </Svg>
  );
}

function TagFavorite({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873l-6.158 -3.245" stroke={color} />
    </Svg>
  );
}

function TagFeature({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 7h3a1 1 0 0 0 1 -1v-1a2 2 0 0 1 4 0v1a1 1 0 0 0 1 1h3a1 1 0 0 1 1 1v3a1 1 0 0 0 1 1h1a2 2 0 0 1 0 4h-1a1 1 0 0 0 -1 1v3a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-1a2 2 0 0 0 -4 0v1a1 1 0 0 1 -1 1h-3a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1h1a2 2 0 0 0 0 -4h-1a1 1 0 0 1 -1 -1v-3a1 1 0 0 1 1 -1" stroke={color} />
    </Svg>
  );
}

function TagHighPriority({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 9v4" stroke={color} />
      <Path d="M10.363 3.591l-8.106 13.534a1.914 1.914 0 0 0 1.636 2.871h16.214a1.914 1.914 0 0 0 1.636 -2.87l-8.106 -13.536a1.914 1.914 0 0 0 -3.274 0" stroke={color} />
      <Path d="M12 16h.01" stroke={color} />
    </Svg>
  );
}

function TagInProgress({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M7 4v16l13 -8l-13 -8" stroke={color} />
    </Svg>
  );
}

function TagLowPriority({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 5l0 14" stroke={color} />
      <Path d="M18 13l-6 6" stroke={color} />
      <Path d="M6 13l6 6" stroke={color} />
    </Svg>
  );
}

function TagOnHold({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M6 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -12" stroke={color} />
      <Path d="M14 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1l0 -12" stroke={color} />
    </Svg>
  );
}

function TagResearch({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 21h14" stroke={color} />
      <Path d="M6 18h2" stroke={color} />
      <Path d="M7 18v3" stroke={color} />
      <Path d="M9 11l3 3l6 -6l-3 -3l-6 6" stroke={color} />
      <Path d="M10.5 12.5l-1.5 1.5" stroke={color} />
      <Path d="M17 3l3 3" stroke={color} />
      <Path d="M12 21a6 6 0 0 0 3.715 -10.712" stroke={color} />
    </Svg>
  );
}

function TagTesting({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M20 8.04l-12.122 12.124a2.857 2.857 0 1 1 -4.041 -4.04l12.122 -12.124" stroke={color} />
      <Path d="M7 13h8" stroke={color} />
      <Path d="M19 15l1.5 1.6a2 2 0 1 1 -3 0l1.5 -1.6" stroke={color} />
      <Path d="M15 3l6 6" stroke={color} />
    </Svg>
  );
}

function TagTodo({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M9 11l3 3l8 -8" stroke={color} />
      <Path d="M20 12v6a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h9" stroke={color} />
    </Svg>
  );
}

function CmdApi({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 13h5" stroke={color} />
      <Path d="M12 16v-8h3a2 2 0 0 1 2 2v1a2 2 0 0 1 -2 2h-3" stroke={color} />
      <Path d="M20 8v8" stroke={color} />
      <Path d="M9 16v-5.5a2.5 2.5 0 0 0 -5 0v5.5" stroke={color} />
    </Svg>
  );
}

function CmdArchive({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M2 5a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2a2 2 0 0 1 -2 2h-16a2 2 0 0 1 -2 -2z" fill={color} />
      <Path d="M19 9c.513 0 .936 .463 .993 1.06l.007 .14v7.2c0 1.917 -1.249 3.484 -2.824 3.594l-.176 .006h-10c-1.598 0 -2.904 -1.499 -2.995 -3.388l-.005 -.212v-7.2c0 -.663 .448 -1.2 1 -1.2h14zm-5 2h-4l-.117 .007a1 1 0 0 0 0 1.986l.117 .007h4l.117 -.007a1 1 0 0 0 0 -1.986l-.117 -.007z" fill={color} />
    </Svg>
  );
}

function CmdBell({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M14.235 19c.865 0 1.322 1.024 .745 1.668a3.992 3.992 0 0 1 -2.98 1.332a3.992 3.992 0 0 1 -2.98 -1.332c-.552 -.616 -.158 -1.579 .634 -1.661l.11 -.006h4.471z" fill={color} />
      <Path d="M12 2c1.358 0 2.506 .903 2.875 2.141l.046 .171l.008 .043a8.013 8.013 0 0 1 4.024 6.069l.028 .287l.019 .289v2.931l.021 .136a3 3 0 0 0 1.143 1.847l.167 .117l.162 .099c.86 .487 .56 1.766 -.377 1.864l-.116 .006h-16c-1.028 0 -1.387 -1.364 -.493 -1.87a3 3 0 0 0 1.472 -2.063l.021 -.143l.001 -2.97a8 8 0 0 1 3.821 -6.454l.248 -.146l.01 -.043a3.003 3.003 0 0 1 2.562 -2.29l.182 -.017l.176 -.004z" fill={color} />
    </Svg>
  );
}

function CmdBolt({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M13 2l.018 .001l.016 .001l.083 .005l.011 .002h.011l.038 .009l.052 .008l.016 .006l.011 .001l.029 .011l.052 .014l.019 .009l.015 .004l.028 .014l.04 .017l.021 .012l.022 .01l.023 .015l.031 .017l.034 .024l.018 .011l.013 .012l.024 .017l.038 .034l.022 .017l.008 .01l.014 .012l.036 .041l.026 .027l.006 .009c.12 .147 .196 .322 .218 .513l.001 .012l.002 .041l.004 .064v6h5a1 1 0 0 1 .868 1.497l-.06 .091l-8 11c-.568 .783 -1.808 .38 -1.808 -.588v-6h-5a1 1 0 0 1 -.868 -1.497l.06 -.091l8 -11l.01 -.013l.018 -.024l.033 -.038l.018 -.022l.009 -.008l.013 -.014l.04 -.036l.028 -.026l.008 -.006a1 1 0 0 1 .402 -.199l.011 -.001l.027 -.005l.074 -.013l.011 -.001l.041 -.002z" fill={color} />
    </Svg>
  );
}

function CmdBook({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M21.5 5.134a1 1 0 0 1 .493 .748l.007 .118v13a1 1 0 0 1 -1.5 .866a8 8 0 0 0 -7.5 -.266v-15.174a10 10 0 0 1 8.5 .708m-10.5 -.707l.001 15.174a8 8 0 0 0 -7.234 .117l-.327 .18l-.103 .044l-.049 .016l-.11 .026l-.061 .01l-.117 .006h-.042l-.11 -.012l-.077 -.014l-.108 -.032l-.126 -.056l-.095 -.056l-.089 -.067l-.06 -.056l-.073 -.082l-.064 -.089l-.022 -.036l-.032 -.06l-.044 -.103l-.016 -.049l-.026 -.11l-.01 -.061l-.004 -.049l-.002 -13.068a1 1 0 0 1 .5 -.866a10 10 0 0 1 8.5 -.707" fill={color} />
    </Svg>
  );
}

function CmdBrain({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M15.5 13a3.5 3.5 0 0 0 -3.5 3.5v1a3.5 3.5 0 0 0 7 0v-1.8" stroke={color} />
      <Path d="M8.5 13a3.5 3.5 0 0 1 3.5 3.5v1a3.5 3.5 0 0 1 -7 0v-1.8" stroke={color} />
      <Path d="M17.5 16a3.5 3.5 0 0 0 0 -7h-.5" stroke={color} />
      <Path d="M19 9.3v-2.8a3.5 3.5 0 0 0 -7 0" stroke={color} />
      <Path d="M6.5 16a3.5 3.5 0 0 1 0 -7h.5" stroke={color} />
      <Path d="M5 9.3v-2.8a3.5 3.5 0 0 1 7 0v10" stroke={color} />
    </Svg>
  );
}

function CmdBraces({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M7 4a2 2 0 0 0 -2 2v3a2 3 0 0 1 -2 3a2 3 0 0 1 2 3v3a2 2 0 0 0 2 2" stroke={color} />
      <Path d="M17 4a2 2 0 0 1 2 2v3a2 3 0 0 0 2 3a2 3 0 0 0 -2 3v3a2 2 0 0 1 -2 2" stroke={color} />
    </Svg>
  );
}

function CmdBrandDocker({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M22 12.54c-1.804 -.345 -2.701 -1.08 -3.523 -2.94c-.487 .696 -1.102 1.568 -.92 2.4c.028 .238 -.32 1 -.557 1h-14c0 5.208 3.164 7 6.196 7c4.124 .022 7.828 -1.376 9.854 -5c1.146 -.101 2.296 -1.505 2.95 -2.46" stroke={color} />
      <Path d="M5 10h3v3h-3l0 -3" stroke={color} />
      <Path d="M8 10h3v3h-3l0 -3" stroke={color} />
      <Path d="M11 10h3v3h-3l0 -3" stroke={color} />
      <Path d="M8 7h3v3h-3l0 -3" stroke={color} />
      <Path d="M11 7h3v3h-3l0 -3" stroke={color} />
      <Path d="M11 4h3v3h-3l0 -3" stroke={color} />
      <Path d="M4.571 18c1.5 0 2.047 -.074 2.958 -.78" stroke={color} />
      <Path d="M10 16l0 .01" stroke={color} />
    </Svg>
  );
}

function CmdBrandGithub({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M5.315 2.1c.791 -.113 1.9 .145 3.333 .966l.272 .161l.16 .1l.397 -.083a13.3 13.3 0 0 1 4.59 -.08l.456 .08l.396 .083l.161 -.1c1.385 -.84 2.487 -1.17 3.322 -1.148l.164 .008l.147 .017l.076 .014l.05 .011l.144 .047a1 1 0 0 1 .53 .514a5.2 5.2 0 0 1 .397 2.91l-.047 .267l-.046 .196l.123 .163c.574 .795 .93 1.728 1.03 2.707l.023 .295l.007 .272c0 3.855 -1.659 5.883 -4.644 6.68l-.245 .061l-.132 .029l.014 .161l.008 .157l.004 .365l-.002 .213l-.003 3.834a1 1 0 0 1 -.883 .993l-.117 .007h-6a1 1 0 0 1 -.993 -.883l-.007 -.117v-.734c-1.818 .26 -3.03 -.424 -4.11 -1.878l-.535 -.766c-.28 -.396 -.455 -.579 -.589 -.644l-.048 -.019a1 1 0 0 1 .564 -1.918c.642 .188 1.074 .568 1.57 1.239l.538 .769c.76 1.079 1.36 1.459 2.609 1.191l.001 -.678l-.018 -.168a5.03 5.03 0 0 1 -.021 -.824l.017 -.185l.019 -.12l-.108 -.024c-2.976 -.71 -4.703 -2.573 -4.875 -6.139l-.01 -.31l-.004 -.292a5.6 5.6 0 0 1 .908 -3.051l.152 -.222l.122 -.163l-.045 -.196a5.2 5.2 0 0 1 .145 -2.642l.1 -.282l.106 -.253a1 1 0 0 1 .529 -.514l.144 -.047l.154 -.03z" fill={color} />
    </Svg>
  );
}

function CmdBrandPython({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 9h-7a2 2 0 0 0 -2 2v4a2 2 0 0 0 2 2h3" stroke={color} />
      <Path d="M12 15h7a2 2 0 0 0 2 -2v-4a2 2 0 0 0 -2 -2h-3" stroke={color} />
      <Path d="M8 9v-4a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v5a2 2 0 0 1 -2 2h-4a2 2 0 0 0 -2 2v5a2 2 0 0 0 2 2h4a2 2 0 0 0 2 -2v-4" stroke={color} />
      <Path d="M11 6l0 .01" stroke={color} />
      <Path d="M13 18l0 .01" stroke={color} />
    </Svg>
  );
}

function CmdBrandReact({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M6.306 8.711c-2.602 .723 -4.306 1.926 -4.306 3.289c0 2.21 4.477 4 10 4c.773 0 1.526 -.035 2.248 -.102" stroke={color} />
      <Path d="M17.692 15.289c2.603 -.722 4.308 -1.926 4.308 -3.289c0 -2.21 -4.477 -4 -10 -4c-.773 0 -1.526 .035 -2.25 .102" stroke={color} />
      <Path d="M6.305 15.287c-.676 2.615 -.485 4.693 .695 5.373c1.913 1.105 5.703 -1.877 8.464 -6.66c.387 -.67 .733 -1.339 1.036 -2" stroke={color} />
      <Path d="M17.694 8.716c.677 -2.616 .487 -4.696 -.694 -5.376c-1.913 -1.105 -5.703 1.877 -8.464 6.66c-.387 .67 -.733 1.34 -1.037 2" stroke={color} />
      <Path d="M12 5.424c-1.925 -1.892 -3.82 -2.766 -5 -2.084c-1.913 1.104 -1.226 5.877 1.536 10.66c.386 .67 .793 1.304 1.212 1.896" stroke={color} />
      <Path d="M12 18.574c1.926 1.893 3.821 2.768 5 2.086c1.913 -1.104 1.226 -5.877 -1.536 -10.66c-.375 -.65 -.78 -1.283 -1.212 -1.897" stroke={color} />
      <Path d="M11.5 12.866a1 1 0 1 0 1 -1.732a1 1 0 0 0 -1 1.732" stroke={color} />
    </Svg>
  );
}

function CmdBrandVscode({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M16 3v18l4 -2.5v-13l-4 -2.5" stroke={color} />
      <Path d="M9.165 13.903l-4.165 3.597l-2 -1l4.333 -4.5m1.735 -1.802l6.932 -7.198v5l-4.795 4.141" stroke={color} />
      <Path d="M16 16.5l-11 -10l-2 1l13 13.5" stroke={color} />
    </Svg>
  );
}

function CmdBug({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M12 4a4 4 0 0 1 3.995 3.8l.005 .2a1 1 0 0 1 .428 .096l3.033 -1.938a1 1 0 1 1 1.078 1.684l-3.015 1.931a7.17 7.17 0 0 1 .476 2.227h3a1 1 0 0 1 0 2h-3v1a6.01 6.01 0 0 1 -.195 1.525l2.708 1.616a1 1 0 1 1 -1.026 1.718l-2.514 -1.501a6.002 6.002 0 0 1 -3.973 2.56v-5.918a1 1 0 0 0 -2 0v5.917a6.002 6.002 0 0 1 -3.973 -2.56l-2.514 1.503a1 1 0 1 1 -1.026 -1.718l2.708 -1.616a6.01 6.01 0 0 1 -.195 -1.526v-1h-3a1 1 0 0 1 0 -2h3.001v-.055a7 7 0 0 1 .474 -2.173l-3.014 -1.93a1 1 0 1 1 1.078 -1.684l3.032 1.939l.024 -.012l.068 -.027l.019 -.005l.016 -.006l.032 -.008l.04 -.013l.034 -.007l.034 -.004l.045 -.008l.015 -.001l.015 -.002l.087 -.004a4 4 0 0 1 4 -4zm0 2a2 2 0 0 0 -2 2h4a2 2 0 0 0 -2 -2z" fill={color} />
    </Svg>
  );
}

function CmdChartBar({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 13a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -6" stroke={color} />
      <Path d="M15 9a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v10a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -10" stroke={color} />
      <Path d="M9 5a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v14a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1l0 -14" stroke={color} />
      <Path d="M4 20h14" stroke={color} />
    </Svg>
  );
}

function CmdChecklist({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M9.615 20h-2.615a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8" stroke={color} />
      <Path d="M14 19l2 2l4 -4" stroke={color} />
      <Path d="M9 8h4" stroke={color} />
      <Path d="M9 12h2" stroke={color} />
    </Svg>
  );
}

function CmdClock({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M17 3.34a10 10 0 1 1 -14.995 8.984l-.005 -.324l.005 -.324a10 10 0 0 1 14.995 -8.336zm-5 2.66a1 1 0 0 0 -.993 .883l-.007 .117v5l.009 .131a1 1 0 0 0 .197 .477l.087 .1l3 3l.094 .082a1 1 0 0 0 1.226 0l.094 -.083l.083 -.094a1 1 0 0 0 0 -1.226l-.083 -.094l-2.707 -2.708v-4.585l-.007 -.117a1 1 0 0 0 -.993 -.883z" fill={color} />
    </Svg>
  );
}

function CmdCloud({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M10.04 4.305c2.195 -.667 4.615 -.224 6.36 1.176c1.386 1.108 2.188 2.686 2.252 4.34l.003 .212l.091 .003c2.3 .107 4.143 1.961 4.25 4.27l.004 .211c0 2.407 -1.885 4.372 -4.255 4.482l-.21 .005h-11.878l-.222 -.008c-2.94 -.11 -5.317 -2.399 -5.43 -5.263l-.005 -.216c0 -2.747 2.08 -5.01 4.784 -5.417l.114 -.016l.07 -.181c.663 -1.62 2.056 -2.906 3.829 -3.518l.244 -.08z" fill={color} />
    </Svg>
  );
}

function CmdCode({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M7 8l-4 4l4 4" stroke={color} />
      <Path d="M17 8l4 4l-4 4" stroke={color} />
      <Path d="M14 4l-4 16" stroke={color} />
    </Svg>
  );
}

function CmdCommand({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M7 9a2 2 0 1 1 2 -2v10a2 2 0 1 1 -2 -2h10a2 2 0 1 1 -2 2v-10a2 2 0 1 1 2 2h-10" stroke={color} />
    </Svg>
  );
}

function CmdCpu({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 6a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -12" stroke={color} />
      <Path d="M9 9h6v6h-6l0 -6" stroke={color} />
      <Path d="M3 10h2" stroke={color} />
      <Path d="M3 14h2" stroke={color} />
      <Path d="M10 3v2" stroke={color} />
      <Path d="M14 3v2" stroke={color} />
      <Path d="M21 10h-2" stroke={color} />
      <Path d="M21 14h-2" stroke={color} />
      <Path d="M14 21v-2" stroke={color} />
      <Path d="M10 21v-2" stroke={color} />
    </Svg>
  );
}

function CmdDatabase({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M3 15.731c1.968 1.507 5.234 2.269 9 2.269c3.76 0 7.025 -.76 9 -2.252v2.252c0 2.425 -3.895 3.936 -8.693 3.998l-.307 .002c-4.938 0 -9 -1.523 -9 -4z" fill={color} />
      <Path d="M3 9.731c1.968 1.507 5.234 2.269 9 2.269c3.76 0 7.025 -.76 9 -2.252v2.252c0 2.477 -4.062 4 -9 4c-4.798 0 -8.77 -1.438 -8.979 -3.795l-.016 -.101l-.005 -.104z" fill={color} />
      <Path d="M12 2c1.041 0 2.044 .068 2.977 .198l.469 .071q .84 .14 1.586 .348l.44 .131l.075 .024a11 11 0 0 1 .805 .3l.199 .086q .535 .242 .967 .53q .165 .11 .313 .225a3.8 3.8 0 0 1 .669 .668l.091 .128q .07 .105 .129 .211l.07 .139q .163 .35 .2 .73l.01 .211c0 2.477 -4.062 4 -9 4c-4.798 0 -8.77 -1.438 -8.979 -3.795a1 1 0 0 1 -.021 -.205l.005 -.104l.016 -.1c.205 -2.306 4.01 -3.733 8.667 -3.794z" fill={color} />
    </Svg>
  );
}

function CmdDeviceDesktop({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M7 21a1 1 0 0 1 0 -2h1v-2h-4a2 2 0 0 1 -2 -2v-10a2 2 0 0 1 2 -2h16a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-4v2h1a1 1 0 0 1 0 2zm7 -4h-4v2h4z" fill={color} />
    </Svg>
  );
}

function CmdDeviceLaptop({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 19l18 0" stroke={color} />
      <Path d="M5 7a1 1 0 0 1 1 -1h12a1 1 0 0 1 1 1v8a1 1 0 0 1 -1 1h-12a1 1 0 0 1 -1 -1l0 -8" stroke={color} />
    </Svg>
  );
}

function CmdDownload({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M20 16a1 1 0 0 1 1 1v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3v-2a1 1 0 0 1 2 0v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1 -1v-2a1 1 0 0 1 1 -1m-8 -13a1 1 0 0 1 1 1v9.585l3.293 -3.292a1 1 0 0 1 1.414 1.414l-5 5a1 1 0 0 1 -.09 .08l.09 -.08a1 1 0 0 1 -.674 .292l-.033 .001h-.032l-.054 -.004l.086 .004a1 1 0 0 1 -.617 -.213a1 1 0 0 1 -.09 -.08l-5 -5a1 1 0 0 1 1.414 -1.414l3.293 3.292v-9.585a1 1 0 0 1 1 -1" fill={color} />
    </Svg>
  );
}

function CmdFileCode({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M12 2l.117 .007a1 1 0 0 1 .876 .876l.007 .117v4l.005 .15a2 2 0 0 0 1.838 1.844l.157 .006h4l.117 .007a1 1 0 0 1 .876 .876l.007 .117v9a3 3 0 0 1 -2.824 2.995l-.176 .005h-10a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-14a3 3 0 0 1 2.824 -2.995l.176 -.005zm-1.553 11.106a1 1 0 0 0 -1.341 .447l-1 2a1 1 0 0 0 0 .894l1 2a1 1 0 0 0 1.341 .447l.102 -.058a1 1 0 0 0 .345 -1.283l-.776 -1.553l.776 -1.553a1 1 0 0 0 -.447 -1.341m4.447 .447a1 1 0 0 0 -1.341 -.447l-.102 .058a1 1 0 0 0 -.345 1.283l.774 1.553l-.775 1.553a1 1 0 0 0 1.788 .894l1 -2a1 1 0 0 0 0 -.894z" fill={color} />
      <Path d="M19 7h-4l-.001 -4.001z" fill={color} />
    </Svg>
  );
}

function CmdFileDiff({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M12 2l.117 .007a1 1 0 0 1 .876 .876l.007 .117v4l.005 .15a2 2 0 0 0 1.838 1.844l.157 .006h4l.117 .007a1 1 0 0 1 .876 .876l.007 .117v9a3 3 0 0 1 -2.824 2.995l-.176 .005h-10a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-14a3 3 0 0 1 2.824 -2.995l.176 -.005zm2 15h-4a1 1 0 0 0 0 2h4a1 1 0 0 0 0 -2m-2 -7a1 1 0 0 0 -1 1v1h-1a1 1 0 0 0 0 2h1v1a1 1 0 0 0 2 0v-1h1a1 1 0 0 0 0 -2h-1v-1a1 1 0 0 0 -1 -1" fill={color} />
      <Path d="M19 7h-4l-.001 -4.001z" fill={color} />
    </Svg>
  );
}

function CmdFileSearch({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M14 3v4a1 1 0 0 0 1 1h4" stroke={color} />
      <Path d="M12 21h-5a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v4.5" stroke={color} />
      <Path d="M14 17.5a2.5 2.5 0 1 0 5 0a2.5 2.5 0 1 0 -5 0" stroke={color} />
      <Path d="M18.5 19.5l2.5 2.5" stroke={color} />
    </Svg>
  );
}

function CmdFileText({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M12 2l.117 .007a1 1 0 0 1 .876 .876l.007 .117v4l.005 .15a2 2 0 0 0 1.838 1.844l.157 .006h4l.117 .007a1 1 0 0 1 .876 .876l.007 .117v9a3 3 0 0 1 -2.824 2.995l-.176 .005h-10a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-14a3 3 0 0 1 2.824 -2.995l.176 -.005zm3 14h-6a1 1 0 0 0 0 2h6a1 1 0 0 0 0 -2m0 -4h-6a1 1 0 0 0 0 2h6a1 1 0 0 0 0 -2m-5 -4h-1a1 1 0 1 0 0 2h1a1 1 0 0 0 0 -2" fill={color} />
      <Path d="M19 7h-4l-.001 -4.001z" fill={color} />
    </Svg>
  );
}

function CmdFlask({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M15 2a1 1 0 0 1 0 2v4.826l3.932 10.814l.034 .077a1.7 1.7 0 0 1 -.002 1.193l-.07 .162a1.7 1.7 0 0 1 -1.213 .911l-.181 .017h-11l-.181 -.017a1.7 1.7 0 0 1 -1.285 -2.266l.039 -.09l3.927 -10.804v-4.823a1 1 0 1 1 0 -2h6zm-2 2h-2v4h2v-4z" fill={color} />
    </Svg>
  );
}

function CmdFolder({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M9 3a1 1 0 0 1 .608 .206l.1 .087l2.706 2.707h6.586a3 3 0 0 1 2.995 2.824l.005 .176v8a3 3 0 0 1 -2.824 2.995l-.176 .005h-14a3 3 0 0 1 -2.995 -2.824l-.005 -.176v-11a3 3 0 0 1 2.824 -2.995l.176 -.005h4z" fill={color} />
    </Svg>
  );
}

function CmdFolderOpen({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M2 6c0 -.796 .316 -1.558 .879 -2.121c.563 -.563 1.325 -.879 2.121 -.879h4l.099 .005c.229 .023 .444 .124 .608 .288l2.707 2.707h6.586c.796 0 1.558 .316 2.121 .879c.319 .319 .559 .703 .707 1.121l-14.523 0c-.407 0 -.805 .125 -1.14 .356c-.292 .203 -.525 .48 -.674 .801l-.058 .141l-1.379 3.676c-.194 .517 .068 1.093 .585 1.287c.517 .194 1.094 -.068 1.288 -.585l1.134 -3.027c.146 -.39 .519 -.649 .937 -.649h13.002l.217 .012c.216 .024 .426 .082 .624 .173c.054 .025 .107 .053 .159 .083c.199 .115 .377 .263 .525 .439c.188 .222 .325 .482 .403 .762c.077 .28 .092 .573 .045 .859c-.001 .008 -.003 .016 -.005 .024l-.995 5.21c-.131 .686 -.497 1.304 -1.036 1.749c-.47 .389 -1.046 .624 -1.65 .677l-.261 .012h-14.026c-.796 0 -1.558 -.316 -2.121 -.879c-.563 -.563 -.879 -1.325 -.879 -2.121v-11z" fill={color} />
    </Svg>
  );
}

function CmdGitBranch({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M15 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M7 8l0 8" stroke={color} />
      <Path d="M9 18h6a2 2 0 0 0 2 -2v-5" stroke={color} />
      <Path d="M14 14l3 -3l3 3" stroke={color} />
    </Svg>
  );
}

function CmdGitCommit({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M9 12a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" stroke={color} />
      <Path d="M12 3l0 6" stroke={color} />
      <Path d="M12 15l0 6" stroke={color} />
    </Svg>
  );
}

function CmdGitMerge({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M15 12a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M7 8l0 8" stroke={color} />
      <Path d="M7 8a4 4 0 0 0 4 4h4" stroke={color} />
    </Svg>
  );
}

function CmdGitPullRequest({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M4 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M16 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M6 8l0 8" stroke={color} />
      <Path d="M11 6h5a2 2 0 0 1 2 2v8" stroke={color} />
      <Path d="M14 9l-3 -3l3 -3" stroke={color} />
    </Svg>
  );
}

function CmdKey({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M14.52 2c1.029 0 2.015 .409 2.742 1.136l3.602 3.602a3.877 3.877 0 0 1 0 5.483l-2.643 2.643a3.88 3.88 0 0 1 -4.941 .452l-.105 -.078l-5.882 5.883a3 3 0 0 1 -1.68 .843l-.22 .027l-.221 .009h-1.172c-1.014 0 -1.867 -.759 -1.991 -1.823l-.009 -.177v-1.172c0 -.704 .248 -1.386 .73 -1.96l.149 -.161l.414 -.414a1 1 0 0 1 .707 -.293h1v-1a1 1 0 0 1 .883 -.993l.117 -.007h1v-1a1 1 0 0 1 .206 -.608l.087 -.1l1.468 -1.469l-.076 -.103a3.9 3.9 0 0 1 -.678 -1.963l-.007 -.236c0 -1.029 .409 -2.015 1.136 -2.742l2.643 -2.643a3.88 3.88 0 0 1 2.741 -1.136m.495 5h-.02a2 2 0 1 0 0 4h.02a2 2 0 1 0 0 -4" fill={color} />
    </Svg>
  );
}

function CmdLayoutDashboard({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M9 3a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2zm0 12a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2zm10 -4a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-6a2 2 0 0 1 2 -2zm0 -8a2 2 0 0 1 2 2v2a2 2 0 0 1 -2 2h-4a2 2 0 0 1 -2 -2v-2a2 2 0 0 1 2 -2z" fill={color} />
    </Svg>
  );
}

function CmdLink({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M9 15l6 -6" stroke={color} />
      <Path d="M11 6l.463 -.536a5 5 0 0 1 7.071 7.072l-.534 .464" stroke={color} />
      <Path d="M13 18l-.397 .534a5.068 5.068 0 0 1 -7.127 0a4.972 4.972 0 0 1 0 -7.071l.524 -.463" stroke={color} />
    </Svg>
  );
}

function CmdLock({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M12 2a5 5 0 0 1 5 5v3a3 3 0 0 1 3 3v6a3 3 0 0 1 -3 3h-10a3 3 0 0 1 -3 -3v-6a3 3 0 0 1 3 -3v-3a5 5 0 0 1 5 -5m0 12a2 2 0 0 0 -1.995 1.85l-.005 .15a2 2 0 1 0 2 -2m0 -10a3 3 0 0 0 -3 3v3h6v-3a3 3 0 0 0 -3 -3" fill={color} />
    </Svg>
  );
}

function CmdMessageCircle({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M5.821 4.91c3.899 -2.765 9.468 -2.539 13.073 .535c3.667 3.129 4.168 8.238 1.152 11.898c-2.841 3.447 -7.965 4.583 -12.231 2.805l-.233 -.101l-4.374 .931l-.04 .006l-.035 .007h-.018l-.022 .005h-.038l-.033 .004l-.021 -.001l-.023 .001l-.033 -.003h-.035l-.022 -.004l-.022 -.002l-.035 -.007l-.034 -.005l-.016 -.004l-.024 -.005l-.049 -.016l-.024 -.005l-.011 -.005l-.022 -.007l-.045 -.02l-.03 -.012l-.011 -.006l-.014 -.006l-.031 -.018l-.045 -.024l-.016 -.011l-.037 -.026l-.04 -.027l-.002 -.004l-.013 -.009l-.043 -.04l-.025 -.02l-.006 -.007l-.056 -.062l-.013 -.014l-.011 -.014l-.039 -.056l-.014 -.019l-.005 -.01l-.042 -.073l-.007 -.012l-.004 -.008l-.007 -.012l-.014 -.038l-.02 -.042l-.004 -.016l-.004 -.01l-.017 -.061l-.007 -.018l-.002 -.015l-.005 -.019l-.005 -.033l-.008 -.042l-.002 -.031l-.003 -.01v-.016l-.004 -.054l.001 -.036l.001 -.023l.002 -.053l.004 -.025v-.019l.008 -.035l.005 -.034l.005 -.02l.004 -.02l.018 -.06l.003 -.013l1.15 -3.45l-.022 -.037c-2.21 -3.747 -1.209 -8.391 2.413 -11.119z" fill={color} />
    </Svg>
  );
}

function CmdPackage({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 3l8 4.5l0 9l-8 4.5l-8 -4.5l0 -9l8 -4.5" stroke={color} />
      <Path d="M12 12l8 -4.5" stroke={color} />
      <Path d="M12 12l0 9" stroke={color} />
      <Path d="M12 12l-8 -4.5" stroke={color} />
      <Path d="M16 5.25l-8 4.5" stroke={color} />
    </Svg>
  );
}

function CmdPencilCode({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4" stroke={color} />
      <Path d="M13.5 6.5l4 4" stroke={color} />
      <Path d="M20 21l2 -2l-2 -2" stroke={color} />
      <Path d="M17 17l-2 2l2 2" stroke={color} />
    </Svg>
  );
}

function CmdPlayerPlay({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M6 4v16a1 1 0 0 0 1.524 .852l13 -8a1 1 0 0 0 0 -1.704l-13 -8a1 1 0 0 0 -1.524 .852z" fill={color} />
    </Svg>
  );
}

function CmdRefresh({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M20 11a8.1 8.1 0 0 0 -15.5 -2m-.5 -4v4h4" stroke={color} />
      <Path d="M4 13a8.1 8.1 0 0 0 15.5 2m.5 4v-4h-4" stroke={color} />
    </Svg>
  );
}

function CmdRobot({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M6 6a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v4a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2l0 -4" stroke={color} />
      <Path d="M12 2v2" stroke={color} />
      <Path d="M9 12v9" stroke={color} />
      <Path d="M15 12v9" stroke={color} />
      <Path d="M5 16l4 -2" stroke={color} />
      <Path d="M15 14l4 2" stroke={color} />
      <Path d="M9 18h6" stroke={color} />
      <Path d="M10 8v.01" stroke={color} />
      <Path d="M14 8v.01" stroke={color} />
    </Svg>
  );
}

function CmdRoute({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 19a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" stroke={color} />
      <Path d="M19 7a2 2 0 1 0 0 -4a2 2 0 0 0 0 4" stroke={color} />
      <Path d="M11 19h5.5a3.5 3.5 0 0 0 0 -7h-8a3.5 3.5 0 0 1 0 -7h4.5" stroke={color} />
    </Svg>
  );
}

function CmdRocket({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 13a8 8 0 0 1 7 7a6 6 0 0 0 3 -5a9 9 0 0 0 6 -8a3 3 0 0 0 -3 -3a9 9 0 0 0 -8 6a6 6 0 0 0 -5 3" stroke={color} />
      <Path d="M7 14a6 6 0 0 0 -3 6a6 6 0 0 0 6 -3" stroke={color} />
      <Path d="M14 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" stroke={color} />
    </Svg>
  );
}

function CmdSearch({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M14 3.072a8 8 0 0 1 2.32 11.834l5.387 5.387a1 1 0 0 1 -1.414 1.414l-5.388 -5.387a8 8 0 1 1 -.905 -13.249" fill={color} />
    </Svg>
  );
}

function CmdServer({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 7a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3" stroke={color} />
      <Path d="M3 15a3 3 0 0 1 3 -3h12a3 3 0 0 1 3 3v2a3 3 0 0 1 -3 3h-12a3 3 0 0 1 -3 -3l0 -2" stroke={color} />
      <Path d="M7 8l0 .01" stroke={color} />
      <Path d="M7 16l0 .01" stroke={color} />
    </Svg>
  );
}

function CmdSettings({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M14.647 4.081a.724 .724 0 0 0 1.08 .448c2.439 -1.485 5.23 1.305 3.745 3.744a.724 .724 0 0 0 .447 1.08c2.775 .673 2.775 4.62 0 5.294a.724 .724 0 0 0 -.448 1.08c1.485 2.439 -1.305 5.23 -3.744 3.745a.724 .724 0 0 0 -1.08 .447c-.673 2.775 -4.62 2.775 -5.294 0a.724 .724 0 0 0 -1.08 -.448c-2.439 1.485 -5.23 -1.305 -3.745 -3.744a.724 .724 0 0 0 -.447 -1.08c-2.775 -.673 -2.775 -4.62 0 -5.294a.724 .724 0 0 0 .448 -1.08c-1.485 -2.439 1.305 -5.23 3.744 -3.745a.722 .722 0 0 0 1.08 -.447c.673 -2.775 4.62 -2.775 5.294 0zm-2.647 4.919a3 3 0 1 0 0 6a3 3 0 0 0 0 -6" fill={color} />
    </Svg>
  );
}

function CmdShieldSearch({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M12 21a12 12 0 0 1 -8.5 -15a12 12 0 0 0 8.5 -3a12 12 0 0 0 8.5 3c.539 1.832 .627 3.747 .283 5.588" stroke={color} />
      <Path d="M15 18a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" stroke={color} />
      <Path d="M20.2 20.2l1.8 1.8" stroke={color} />
    </Svg>
  );
}

function CmdSparkles({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M16 19a1 1 0 0 1 0 -2a1 1 0 0 0 1 -1c0 -1.333 2 -1.333 2 0a1 1 0 0 0 1 1c1.333 0 1.333 2 0 2a1 1 0 0 0 -1 1c0 1.333 -2 1.333 -2 0a1 1 0 0 0 -1 -1" fill={color} />
      <Path d="M3 11a5 5 0 0 0 5 -5c0 -1.333 2 -1.333 2 0a5 5 0 0 0 5 5c1.333 0 1.333 2 0 2a5 5 0 0 0 -5 5a1 1 0 0 1 -2 0a5 5 0 0 0 -5 -5c-1.333 0 -1.333 -2 0 -2" fill={color} />
      <Path d="M16 7a1 1 0 0 1 0 -2a1 1 0 0 0 1 -1c0 -1.333 2 -1.333 2 0a1 1 0 0 0 1 1c1.333 0 1.333 2 0 2a1 1 0 0 0 -1 1c0 1.333 -2 1.333 -2 0a1 1 0 0 0 -1 -1" fill={color} />
    </Svg>
  );
}

function CmdStack({ size, color }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill={color}>
      <Path d="M20.894 13.553a1 1 0 0 1 -.447 1.341l-8 4a1 1 0 0 1 -.894 0l-8 -4a1 1 0 0 1 .894 -1.788l7.553 3.774l7.554 -3.775a1 1 0 0 1 1.341 .447m-8.887 -8.552q .056 0 .111 .007l.111 .02l.086 .024l.012 .006l.012 .002l.029 .014l.05 .019l.016 .009l.012 .005l8 4a1 1 0 0 1 0 1.788l-8 4a1 1 0 0 1 -.894 0l-8 -4a1 1 0 0 1 0 -1.788l8 -4l.011 -.005l.018 -.01l.078 -.032l.011 -.002l.013 -.006l.086 -.024l.11 -.02l.056 -.005z" fill={color} />
    </Svg>
  );
}

function CmdTerminal({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M8 9l3 3l-3 3" stroke={color} />
      <Path d="M13 15l3 0" stroke={color} />
      <Path d="M3 6a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2l0 -12" stroke={color} />
    </Svg>
  );
}

function CmdTestPipe({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M20 8.04l-12.122 12.124a2.857 2.857 0 1 1 -4.041 -4.04l12.122 -12.124" stroke={color} />
      <Path d="M7 13h8" stroke={color} />
      <Path d="M19 15l1.5 1.6a2 2 0 1 1 -3 0l1.5 -1.6" stroke={color} />
      <Path d="M15 3l6 6" stroke={color} />
    </Svg>
  );
}

function CmdTool({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M7 10h3v-3l-3.5 -3.5a6 6 0 0 1 8 8l6 6a2 2 0 0 1 -3 3l-6 -6a6 6 0 0 1 -8 -8l3.5 3.5" stroke={color} />
    </Svg>
  );
}

function CmdUpload({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2" stroke={color} />
      <Path d="M7 9l5 -5l5 5" stroke={color} />
      <Path d="M12 4l0 12" stroke={color} />
    </Svg>
  );
}

function CmdWand({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M6 21l15 -15l-3 -3l-15 15l3 3" stroke={color} />
      <Path d="M15 6l3 3" stroke={color} />
      <Path d="M9 3a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2" stroke={color} />
      <Path d="M19 13a2 2 0 0 0 2 2a2 2 0 0 0 -2 2a2 2 0 0 0 -2 -2a2 2 0 0 0 2 -2" stroke={color} />
    </Svg>
  );
}

function CmdWorld({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0" stroke={color} />
      <Path d="M3.6 9h16.8" stroke={color} />
      <Path d="M3.6 15h16.8" stroke={color} />
      <Path d="M11.5 3a17 17 0 0 0 0 18" stroke={color} />
      <Path d="M12.5 3a17 17 0 0 1 0 18" stroke={color} />
    </Svg>
  );
}

function FallbackFolder({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 4h4l3 3h7a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2" stroke={color} />
    </Svg>
  );
}

function FallbackFolderOpen({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 19l2.757 -7.351a1 1 0 0 1 .936 -.649h12.307a1 1 0 0 1 .986 1.164l-.996 5.211a2 2 0 0 1 -1.964 1.625h-14.026a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2h4l3 3h7a2 2 0 0 1 2 2v2" stroke={color} />
    </Svg>
  );
}

function FallbackWorktree({ size, color, strokeWidth = 1.9 }: TablerIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round">
      <Path d="M5 18a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M5 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M15 6a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" stroke={color} />
      <Path d="M7 8l0 8" stroke={color} />
      <Path d="M9 18h6a2 2 0 0 0 2 -2v-5" stroke={color} />
      <Path d="M14 14l3 -3l3 3" stroke={color} />
    </Svg>
  );
}

/** Session tag glyphs, keyed by the persisted tag value. */
export const TAG_ICONS: Record<string, TablerIconComponent> = {
  "blocked": TagBlocked,
  "bug": TagBug,
  "design": TagDesign,
  "done": TagDone,
  "favorite": TagFavorite,
  "feature": TagFeature,
  "high-priority": TagHighPriority,
  "in-progress": TagInProgress,
  "low-priority": TagLowPriority,
  "on-hold": TagOnHold,
  "research": TagResearch,
  "testing": TagTesting,
  "todo": TagTodo,
};

/** Project identity glyphs, keyed by SIDEBAR_COMMAND_ICON_IDS. */
export const COMMAND_ICONS: Record<string, TablerIconComponent> = {
  "api": CmdApi,
  "archive": CmdArchive,
  "bell": CmdBell,
  "bolt": CmdBolt,
  "book": CmdBook,
  "brain": CmdBrain,
  "braces": CmdBraces,
  "brandDocker": CmdBrandDocker,
  "brandGithub": CmdBrandGithub,
  "brandPython": CmdBrandPython,
  "brandReact": CmdBrandReact,
  "brandVscode": CmdBrandVscode,
  "bug": CmdBug,
  "chartBar": CmdChartBar,
  "checklist": CmdChecklist,
  "clock": CmdClock,
  "cloud": CmdCloud,
  "code": CmdCode,
  "command": CmdCommand,
  "cpu": CmdCpu,
  "database": CmdDatabase,
  "deviceDesktop": CmdDeviceDesktop,
  "deviceLaptop": CmdDeviceLaptop,
  "download": CmdDownload,
  "fileCode": CmdFileCode,
  "fileDiff": CmdFileDiff,
  "fileSearch": CmdFileSearch,
  "fileText": CmdFileText,
  "flask": CmdFlask,
  "folder": CmdFolder,
  "folderOpen": CmdFolderOpen,
  "gitBranch": CmdGitBranch,
  "gitCommit": CmdGitCommit,
  "gitMerge": CmdGitMerge,
  "gitPullRequest": CmdGitPullRequest,
  "key": CmdKey,
  "layoutDashboard": CmdLayoutDashboard,
  "link": CmdLink,
  "lock": CmdLock,
  "messageCircle": CmdMessageCircle,
  "package": CmdPackage,
  "pencilCode": CmdPencilCode,
  "playerPlay": CmdPlayerPlay,
  "refresh": CmdRefresh,
  "robot": CmdRobot,
  "route": CmdRoute,
  "rocket": CmdRocket,
  "search": CmdSearch,
  "server": CmdServer,
  "settings": CmdSettings,
  "shieldSearch": CmdShieldSearch,
  "sparkles": CmdSparkles,
  "stack": CmdStack,
  "terminal": CmdTerminal,
  "testPipe": CmdTestPipe,
  "tool": CmdTool,
  "upload": CmdUpload,
  "wand": CmdWand,
  "world": CmdWorld,
};

/** Project-icon fallbacks when a project ships no icon of its own. */
export const PROJECT_FALLBACK_ICONS: Record<string, TablerIconComponent> = {
  "folder": FallbackFolder,
  "folderOpen": FallbackFolderOpen,
  "worktree": FallbackWorktree,
};
